<a href="https://colab.research.google.com/github/AntonyCajamarca/GoogleColab/blob/main/Practicas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practicas de numpy

Autor: Antony Cajamarca

Fecha: 23/04/2026

##Practica_1
---

Ejercicio 1: Crea una lista con los múltiplos de 7 entre 1 y 100 usando comprehension.


In [ ]:
# Múltiplos de 7 entre 1 y 100
multi_7 = [x for x in range(1, 101) if x % 7 == 0]
print(multi_7)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


Ejercicio 2: Dado el diccionario datos = {'a':10, 'b':25, 'c':7, 'd':18}

a) Crea una lista con las claves cuyo valor sea mayor a 12.

In [ ]:
datos = {'a':10, 'b':25, 'c':7, 'd':18}
claves_m = [k for k, v in datos.items() if v > 12]
print(claves_m)

['b', 'd']


b) Crea un nuevo diccionario con esas claves y sus valores al cuadrado.

In [ ]:
nuevo_dict = {k: datos[k]**2 for k in claves_m}
print(nuevo_dict)

{'b': 625, 'd': 324}


Ejercicio 3: Define una función 'resumen(lista)' que retorne un diccionario con:

longitud, suma, promedio, mínimo y máximo de la lista.


In [ ]:
def resumen(lista):
    return {
        'longitud': len(lista),
        'suma': sum(lista),
        'promedio': sum(lista) / len(lista),
        'minimo': min(lista),
        'maximo': max(lista)
    }
print(resumen([10, 20, 30, 40]))

{'longitud': 4, 'suma': 100, 'promedio': 25.0, 'minimo': 10, 'maximo': 40}


Ejercicio 4: Usa map() para aplicar la función potencia(x, 3) a la lista [1,2,3,4,5].

In [ ]:
lista_numeros = [1, 2, 3, 4, 5]

#potencia al cubo
def potencia(base, exponente=3):
    return base ** exponente
#map
resultado = list(map(potencia, lista_numeros))
print(resultado)

[1, 8, 27, 64, 125]


##Practica_2
---

Ejercicio 1:

a) Vector con enteros del 1 al 20.

In [ ]:
import numpy as np
a = np.arange(1, 21)
print("Vector de a:", a)

Vector de a: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


b) Matriz de ceros de 5 filas y 3 columnas.

In [ ]:
b = np.zeros((5, 3))
print("Matriz de b:", b)

Matriz de b: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


c) 10 puntos igualmente espaciados entre -1 y 1 con linspace.

In [ ]:
c = np.linspace(-1, 1, 10)
print("Puntos de c:", c)

Puntos de c: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


Ejercicio 2:

Imprime: shape, dtype, tamaño en bytes (nbytes) y el elemento [2,3].

In [ ]:
np.random.seed(99)
matriz = np.random.randint(0, 50, (4, 4))

print("Matriz:", matriz)
print("shape:", matriz.shape)
print("dtype:", matriz.dtype)
print("nbytes:", matriz.nbytes)

print("Elemento [2,3]:", matriz[2,3])

Matriz: [[ 1 35 40  9]
 [40 18  4  5]
 [ 1 23 35 49]
 [ 1 48 29 38]]
shape: (4, 4)
dtype: int64
nbytes: 128
Elemento [2,3]: 49


Ejercicio 3:

Cuál es la diferencia de dtype entre np.array([1,2,3]) y np.array([1.0,2.0,3.0])? Verifica con código.

In [ ]:
a = np.array([1,2,3])
b = np.array([1.0,2.0,3.0])

print(a.dtype)  # le diferencia por ser entero
print(b.dtype)  # le diferencia por ser numero float

int64
float64


Ejercicio 4:

Crea una matriz identidad 5×5 y verifica que la suma de su diagonales igual a 5 (usa np.trace()).

In [ ]:
I = np.eye(5)

print(I)
print("Suma:", np.trace(I))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Suma: 5.0


##Practica_3
---

Ejercicio 1: Dado A = np.arange(1, 26).reshape(5, 5)

In [ ]:
import numpy as np
A = np.arange(1, 26).reshape(5, 5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


a) Extrae la sub-matriz de las 3 últimas filas y las 3 primeras columnas.



In [ ]:
sub = A[2:, :3]
print(sub)

[[11 12 13]
 [16 17 18]
 [21 22 23]]


b) Extrae la segunda columna completa.

In [ ]:
colum = A[:, 1]
print(colum)

[ 2  7 12 17 22]


c) Extrae los elementos de los ángulos (esquinas) de la matriz.

In [ ]:
es = [A[0,0], A[0,-1], A[-1,0], A[-1,-1]]
print(es)

[np.int64(1), np.int64(5), np.int64(21), np.int64(25)]


Ejercicio 2: Con la misma matriz A:

a) Crea una máscara booleana para los valores mayores a 12.


In [ ]:
mask = A > 12
print(mask)

[[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


b) Reemplaza esos valores por -1 en una copia del array.


In [ ]:
B = A.copy()
B[B > 12] = -1
print(B)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


c) Usa np.where para reemplazar impares por 0 y mantener los pares.

In [ ]:
resul = np.where(A % 2 == 0, A, 0)
print(resul)

[[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


Ejercicio 3: Crea un vector de 24 elementos con arange(24).

In [ ]:
v = np.arange(24)
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


Reorganízalo en: (a) matriz 6×4, (b) tensor 2×3×4, (c) vector fila 1×24

In [ ]:
ma = v.reshape(6, 4)
print(ma)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
ten = v.reshape(2, 3, 4)
print(ten)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
fil = v.reshape(1, 24)
print(fil)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]


Ejercicio 4: Demuestra la diferencia vista vs. copia: modifica un elemento en un slice y verifica que el array original también cambia.

In [ ]:
A = np.arange(1, 10).reshape(3,3)

slice_vista = A[0:2, 0:2]  # VISTA
print("Antes:", A)

slice_vista[0,0] = 999  # se modifica la vista

print("Despues:", A)

Antes: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Despues: [[999   2   3]
 [  4   5   6]
 [  7   8   9]]


##Practica_4
---

Ejercicio 1: Crea una matriz 5×4 de enteros aleatorios entre 1 y 100 (seed=7).

In [ ]:
import numpy as np

np.random.seed(7)
A = np.random.randint(1, 101, (5, 4))
print(A)

[[48 69 26 68]
 [84 24 93 58]
 [15 24 73 90]
 [43 91  9 40]
 [69 49  8 45]]


a) Calcula la media, máximo y mínimo de cada columna.

In [ ]:
print("Med:", A.mean(0))
print("Max:", A.max(0))
print("Min:", A.min(0))

Med: [51.8 51.4 41.8 60.2]
Max: [84 91 93 90]
Min: [15 24  8 40]


b) Calcula la suma acumulada de la primera fila.

In [ ]:
print(np.cumsum(A[0]))

[ 48 117 143 211]


c) Normaliza la matriz para que cada columna tenga valores entre 0 y 1

Fórmula: (x - min_col) / (max_col - min_col)


In [ ]:
min_col = A.min(0)
max_col = A.max(0)

norm = (A - min_col) / (max_col - min_col)
print(norm)

[[0.47826087 0.67164179 0.21176471 0.56      ]
 [1.         0.         1.         0.36      ]
 [0.         0.         0.76470588 1.        ]
 [0.4057971  1.         0.01176471 0.        ]
 [0.7826087  0.37313433 0.         0.1       ]]


Ejercicio 2: Usando broadcasting:

a) Crea un vector fila [1,2,3,4] y un vector columna [[10],[20],[30]].


In [ ]:
fila = np.array([1,2,3,4])
col = np.array([[10],[20],[30]])
print(fila)
print(col)

[1 2 3 4]
[[10]
 [20]
 [30]]


b) Suma ambos vectores y explica el shape del resultado.

In [ ]:
resultado = col + fila
print(resultado)
print("Shape:", resultado.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Shape: (3, 4)


Ejercicio 3: Con el array de notas y nombres del ejemplo de argsort:


In [ ]:
nombres = np.array(['Antony','Jossue','Marco','Raquel','Anghela','Emily'])
notas = np.array([70, 96, 87, 67, 88, 68])

a) ¿Cuántos estudiantes tienen nota mayor al promedio? (usa máscara booleana)

In [ ]:
prom = notas.mean()
mask = notas > prom
print(notas)
print(prom)
print("Cantidad:", np.sum(mask))

[70 96 87 67 88 68]
79.33333333333333
Cantidad: 3


b) Imprime solo los nombres de esos estudiantes.

In [ ]:
print(nombres[mask])
print(notas[mask])

['Jossue' 'Marco' 'Anghela']
[96 87 88]


Ejercicio 4: Crea dos matrices 3×4 y concaténalas vertical y horizontalmente.


In [ ]:
M1 = np.random.randint(1,10,(3,4))
M2 = np.random.randint(1,10,(3,4))
print(M1)
print(M2)

[[7 8 8 4]
 [1 8 8 8]
 [1 6 5 4]]
[[2 4 2 4]
 [5 4 2 6]
 [2 3 4 3]]


Vertical

In [ ]:
vert = np.concatenate([M1, M2], axis=0)
print(vert)

[[7 8 8 4]
 [1 8 8 8]
 [1 6 5 4]
 [2 4 2 4]
 [5 4 2 6]
 [2 3 4 3]]


Horizontal

In [ ]:
hori = np.concatenate([M1, M2], axis=1)
print(hori)

[[7 8 8 4 2 4 2 4]
 [1 8 8 8 5 4 2 6]
 [1 6 5 4 2 3 4 3]]


Luego divide el resultado vertical en 3 partes iguales con vsplit.

In [ ]:
part = np.vsplit(vert, 3)

for p in part:
    print(p)

[[7 8 8 4]
 [1 8 8 8]]
[[1 6 5 4]
 [2 4 2 4]]
[[5 4 2 6]
 [2 3 4 3]]


### 1. Configure Git with your GitHub Personal Access Token

In [ ]:
# Import necessary modules
from google.colab import userdata
import os

# Retrieve the GitHub Token from Colab Secrets
GH_TOKEN = userdata.get('GH_TOKEN')

# Configure Git with your GitHub username and email
# Replace 'YOUR_GITHUB_USERNAME' and 'YOUR_GITHUB_EMAIL' with your actual details
!git config --global user.name "YOUR_GITHUB_USERNAME"
!git config --global user.email "YOUR_GITHUB_EMAIL"

# Use the PAT for authentication
!git config --global credential.helper store


### 2. Clone the Repository

In [ ]:
# Clone your repository
# The token is embedded in the URL for authentication.
repo_url = "https://github.com/AntonyCajamarca/GoogleColab.git"
repo_name = repo_url.split('/')[-1].replace('.git', '')
!git clone https://{GH_TOKEN}@github.com/AntonyCajamarca/GoogleColab.git

# Change to the repository directory
os.chdir(repo_name)


### 3. Copy the Notebook to the Repository

In [ ]:
# Copy the current notebook to the cloned repository directory.
# IMPORTANT: Replace 'Practicas_de_numpy.ipynb' with the actual filename of your current notebook.
# You might need to save your notebook first if it's currently named 'Untitled.ipynb'
notebook_filename = "Practicas_de_numpy.ipynb" # <--- CHANGE THIS IF YOUR NOTEBOOK HAS A DIFFERENT NAME
!cp /content/{notebook_filename} .


### 4. Add, Commit, and Push Changes

In [ ]:
# Add the notebook to the staging area
!git add {notebook_filename}

# Commit the changes
!git commit -m "Add Practicas_de_numpy notebook via Colab"

# Push the changes to your GitHub repository
!git push

print(f"Successfully pushed '{notebook_filename}' to {repo_url}")

# Go back to the root content directory (optional)
os.chdir('/content/')
