<a href="https://colab.research.google.com/github/AntonyCajamarca/GoogleColab/blob/main/Taller_numpy_AntonyC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Taller de numpy

Autor: Antony Cajamarca

Fecha: 16/04/2026

## Listas
---


In [ ]:
numeros = [45,23,11,98,3]
mixta = [2,'Hola',3.1416,False]
vacia = []
de_rango = list(range(1,10))

###Acceso por indices
------

In [ ]:
print(numeros[0])
print(numeros[-1])
print(numeros[-2])
print(numeros[-3])


45
98
11
23


###Slicing[inicio: fin:paso]
-------


In [ ]:
print(numeros[1:4])# indice 1,2,3 (n-1) = 3
print(numeros[:3]) #desde el inicio hasta el 2 por (n-1) = 2
print(numeros[3:])#desde el indice n hasta el final apartir del numero que elegiste
print(numeros[::2])#paso de 2 en 2
print(numeros[::-1])#invertida

[23, 11, 98]
[45, 23, 11]
[98]
[45, 11]
[98, 11, 23, 45]


###Metodos principales
----

In [ ]:
numeros.append(60) # agregar al final -> O(1)
numeros.insert(2, 99)#No son idempotentes= no produce el mismo resultado O(n)
numeros.remove(99)
numeros.pop
print(len(numeros),numeros)
#mutables= estos cambian

[45, 23, 99, 99, 99, 11, 98, 3, 60, 60, 60, 60, 60, 60]

#List Comprehensions

In [ ]:
#lista de datos iterable
cuadrados = [x**2 for x in range(1,8)]
pares = [x for x in range(1,11) if x%2==0]
print(cuadrados)
print(pares)

[1, 4, 9, 16, 25, 36, 49]
[2, 4, 6, 8, 10]


Comprehension anidada (matriz)


In [ ]:
tabla = [[i * j for j in range(1,5)] for i in range(1,4)]
print(tabla)


[[1, 2, 3, 4], [2, 4, 6, 8], [3, 6, 9, 12]]
[2, 4, 6, 8, 10]


Transformaciones de tipo

In [ ]:
palabras =['hola','mundo','python']
#duplas son claves de diccionarios
#que es una tabla hash un diccionario que guarda INVESTIGAR
minusculas = [w.lower( )  for w in palabras]
print(minusculas)

['hola', 'mundo', 'python']


##Tuplas
----


creacion

In [ ]:
coordenada = (3.5, -1.2) # tupla de 2 elementos
dimensiones = (28, 28, 3) # alto, ancho, canales (imagen RGB)
unitaria = (42,) # IMPORTANTE: la coma crea la tupla
no_tupla = (42) # esto es sólo el entero 42
print(coordenada)
print(dimensiones)
print(unitaria)
print(no_tupla, type(no_tupla))
#el type es que tipo de variable
#para que sea una dupla se tiene que poner una , al final

(3.5, -1.2)
(28, 28, 3)
(42,)
42 <class 'int'>


Acceso

In [ ]:
print(dimensiones[0])
print(unitaria[-1])
#Tiene que ser unitario significa que debe haber almenos una ,

28
42


In [ ]:
x, y =coordenada
alto, ancho, profundidad = dimensiones
print(x,y,alto,ancho,profundidad)

3.5 -1.2 28 28 3


Las tuplas son inmutables

In [ ]:
dimensiones[0] = 35 #Esto genera error

TypeError: 'tuple' object does not support item assignment

##Diccionarios
-----

Creación

In [ ]:
estudiante = {
'nombre': 'Antony',
'edad': 25,
'notas': [8.5, 9.0, 7.5],
'activo': True,
#0:"Hola",
#123:"Mundo"
#35.4:"13"
}
print(estudiante)

{'nombre': 'Antony', 'edad': 25, 'notas': [8.5, 9.0, 7.5], 'activo': True}


Acceso

In [ ]:
print(estudiante['nombre'])
print(estudiante.get('carrera','N/A'))
#print(estudiante['35.4'])


María
N/A


Modificación

In [ ]:
estudiante['edad'] = 23
estudiante['semestre'] = 6

Iteracion

In [ ]:
for clave, valor in estudiante.items():
    print(f'{clave:12s} → {valor}')

nombre       → Antony
edad         → 25
notas        → [8.5, 9.0, 7.5]
activo       → True


Dict comprehension

In [ ]:
cubos = {x: x**3 for x in range(1, 6)}
for i in cubos:
  print(cubos[i])


1
8
27
64
125


Otros métodos

In [ ]:
elementos = list(estudiante.items())
print(elementos, type(elementos))

[('nombre', 'Antony'), ('edad', 25), ('notas', [8.5, 9.0, 7.5]), ('activo', True)] <class 'list'>


Verificar existencia de clave

In [ ]:
if 'nombre' in estudiante:
 print('La clave existe')

La clave existe


##Funciones
-----

Función básica

In [ ]:
def saludar(nombre):
 return f'Hola, {nombre}!'

Con parámetros por defecto

In [ ]:
def potencia(base, exponente=2):
 '''Eleva base a exponente. Por defecto calcula el cuadrado.'''
 return base ** exponente

print(potencia(4)) # 25 (usa exponente=2 por defecto)
print(potencia(2, 10)) # 1024


16
1024


Retorno múltiple (devuelve una tupla)

In [ ]:
def min_max(lista):
 return min(lista), max(lista) # empaqueta como tupla
minimo, maximo = min_max([3,4,7,8,5]) # desempaqueta
print(minimo, maximo) # 3 8

3 8


Lambda — función anónima

In [ ]:
doble = lambda x: x * 2
print(doble(5)) # 10

10


In [ ]:
#  argumento en funciones de orden superior
nums = [6, 3, 7, 2, 9, 4]
ordenados = sorted(nums, key=lambda x: -x) # orden descendente
# [9, 7, 6, 4, 3, 2]
print(ordenados)

[9, 7, 6, 4, 3, 2]


map y filter

In [ ]:
cuadrados = list(map(lambda x: x**2, nums))
mayores = list(filter(lambda x: x > 4, nums))
print(cuadrados)
print(mayores)


[36, 9, 49, 4, 81, 16]
[6, 7, 9]


##Módulo_2 Funciones
---

Array 1-D (vector)

In [ ]:
import numpy as np

v = np.array([10, 20, 30, 40, 50])
print(v) # [10 20 30 40 50]
print(type(v)) # <class 'numpy.ndarray'>
print(v.dtype) # int64

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64


Array 2-D es para matriz

In [ ]:

M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Upcasting automático

In [ ]:

mix = np.array([1, 2, 3.0]) # int mas float es igual float64
print(mix.dtype)

float64


Forzar tipo de dato

In [ ]:

float32 = np.array([1, 2, 3], dtype=np.float32)
booleano = np.array([0, 1, 0, 1], dtype=bool)
print(float32.dtype)
print(booleano)

float32
[False  True False  True]


##Funciones Creacion Especializadas
---

Arrays de ceros y unos

In [ ]:

ceros = np.zeros((3, 4)) # matriz 3x4 de 0.0
unos = np.ones((2, 5)) # matriz 2x5 de 1.0
print(ceros.shape)

(3, 4)


Identidad_Hacer diagonal

In [ ]:

I = np.eye(4) # 4x4: 1 en diagonal, 0 fuera
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


arange vs linspace

In [ ]:
# arange define el PASO
a = np.arange(0, 10, 2) # stop 10 excluido
# linspace define la CANTIDAD de puntos
b = np.linspace(0, 1, 5) # stop incluido
print('arange: ', a)
print('linspace:', b)

arange:  [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


Aleatorios

In [ ]:
np.random.seed(42) # semilla fija es reproducible
uniforme = np.random.rand(3, 4) # valores de [0,1)
normal = np.random.randn(3, 4) # distribución normal (μ=0, σ=1)
enteros = np.random.randint(1, 10, size=(3, 3)) # enteros en [1, 10)
print(uniforme)
print(normal)
print(enteros)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]
[[-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]]
[[3 7 4]
 [9 3 5]
 [3 7 5]]


##Atributos del ndarray
---

In [ ]:
import numpy as np
A = np.random.randint(0, 100, size=(4, 3, 2)) # tensor 3-D
print('shape: ', A.shape)
print('ndim: ', A.ndim)
print('size: ', A.size)
print('dtype: ', A.dtype)
print('itemsize: ', A.itemsize)
print('nbytes: ', A.nbytes)

shape:  (4, 3, 2)
ndim:  3
size:  24
dtype:  int64
itemsize:  8
nbytes:  192


Diferencia entre shape de vector y matriz

In [ ]:
v = np.array([1, 2, 3, 4, 5])
M = np.array([[1, 2, 3, 4, 5]])
print(v.shape) # vector 1-D con 5 elementos
print(M.shape) # matriz 2-D de 1 fila y 5 columnas

# Son numéricamente equivalentes pero estructuralmente distintos

(5,)
(1, 5)


##Modulo_3
---

In [ ]:
import numpy as np
M = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

Acceso a elementos individuales

In [ ]:
print(M[0, 0]) # fila 0, columna 0
print(M[1, 2]) # fila 1, columna 2
print(M[-1, -1]) # última fila, última columna

10
60
90


Acceso a filas y columnas completas

In [ ]:
# ':'todos los elementos de ese eje'
print(M[0, :]) # fila 0 completa
print(M[:, 1]) # columna 1 completa
print(M[-1, :]) # última fila

[10 20 30]
[20 50 80]
[70 80 90]


Tensor 3-D

In [ ]:
T = np.arange(24).reshape(2, 3, 4) # 2 'páginas', 3 filas, 4 columnas
print(T[0]) # primera 'página' (matriz 3×4)
print(T[1, 2, 3]) # página 1, fila 2, columna 3
print(T[:, 0, :]) # TODAS las páginas

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
23
[[ 0  1  2  3]
 [12 13 14 15]]


#Slicing_SeleccionSubconjuntos

In [ ]:
import numpy as np
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

Slicing básico

In [ ]:
# [fila_ini:fila_fin , col_ini:col_fin]
sub = A[0:1, 1:3] # filas 0, columnas 1-2
print(sub)

[[2 3]]


Omitir índices

In [ ]:
print(A[:2, :]) # 2 primeras filas
print(A[1:, 2:]) # desde fila 1, desde columna 2

[[1 2 3 4]
 [5 6 7 8]]
[[ 7  8]
 [11 12]]


Con paso

In [ ]:
print(A[::2, ::2]) # filas pares, columnas pares
# [[ 1 3]
# [ 9 11]]

[[ 1  3]
 [ 9 11]]


Vista vs. Copia

In [ ]:
vista = A[0, :] # vista
copia = A[0, :].copy() #copia independiente

vista[0] = 999 # modifica A
copia[0] = 888 # NO se modifica A

print(A[0, :])
print(np.shares_memory(A, vista))
print(np.shares_memory(A, copia))

[999   2   3   4]
True
False


#Indexación Booleana

In [ ]:
import numpy as np
datos = np.array([[5, 12, 3, 18],
                  [7, 2, 15, 9],
                  [11, 6, 20, 1]])

Se crea mascara booleana

In [ ]:
mascara = datos > 10
print(mascara)

[[False  True False  True]
 [False False  True False]
 [ True False  True False]]


Aplicar máscara (filtro)

In [ ]:
mayores = datos[mascara] #devuelve los que cumplen con la mascara booleana
print(mayores)

[12 18 15 11 20]


Combinacion de condiciones

In [ ]:
#en este caso seran los valores de 5 al 15
rango = datos[(datos >= 5) & (datos <= 15)]
print(rango)

[ 5 12  7 15  9 11  6]


Modificar elementos con mascara

In [ ]:
#En este se remplaza los valores menores a 5 remplazando a 0
copia = datos.copy()
copia[copia < 5] = 0
print(copia)

[[ 5 12  0 18]
 [ 7  0 15  9]
 [11  6 20  0]]


Condicional vectoriado

In [ ]:
#codigo np.where(cond, valor_si_True, valor_si_false)
resultado = np.where(datos > 10, datos, 0) #deja todos los numeros mayores de 10 y reeamplaza con 0
print (resultado)

[[ 0 12  0 18]
 [ 0  0 15  0]
 [11  0 20  0]]


#Fancy indexing

In [1]:
import numpy as np
N = np.array([[10,11,12],
              [20,21,22],
              [30,31,32],
              [40,41,42]]
)

Seleccion de filas por indice

In [2]:
indices = [0,2,3]
print(N[indices])

[[10 11 12]
 [30 31 32]
 [40 41 42]]


Orden arbitrario los repetidos

In [3]:
print(N[[3,1,3,0]])

[[40 41 42]
 [20 21 22]
 [40 41 42]
 [10 11 12]]


In [5]:
print(N[[1,2,3]])

[[20 21 22]
 [30 31 32]
 [40 41 42]]


 Combinación con slicing

In [13]:
print(N[[0, 2], 0:]) # filas 0 y 1, columnas desde la 0


[[10 11 12]
 [30 31 32]]


Fancy indexing de columnas

In [15]:
cols = [1, 0]
print(N[:, cols]) # columna 1 y columna 0

[[11 10]
 [21 20]
 [31 30]
 [41 40]]


Copia

In [17]:
copia = N[[0, 1]]
copia[0, 0] = 999
print(N[0, 0])

10


#Reshape el Cambio de Forma

In [19]:
v = np.arange(12)
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


Basico de reshape

In [21]:
M2x6 = v.reshape(2, 6) # 2 filas, 6 columnas
M3x4 = v.reshape(3, 4) #no se pueden poner del mismo numero 4,4
M2x2x3= v.reshape(2, 2, 3) # tensor 3-D

Uso de -1 la dimensión automática

In [22]:
auto = v.reshape(-1, 3) #  12/3 = 4 Se pone donde esta el -1 (4,3)
print(auto.shape)
auto2 = v.reshape(2, -1) # 12/2 = 6 aqui es ek mismo caso (2,6)
print(auto2.shape)


(4, 3)
(2, 6)


flatten vs ravel

In [24]:
M = v.reshape(3, 4) # no poner el mismo (4,4)
flat = M.flatten() # este le hace una COPIA
rav = M.ravel() # lo hace VISTA
flat[0] = 999
print(M[0, 0]) #  flatten no modifica el original
rav[0] = 777
print(M[0, 0]) #  ravel SÍ modifica el original (es vista)

0
777


Agregar dimensiones

In [37]:
v1d = np.array([1, 2, 3, 4]) # shape (4,)
col = v1d.reshape(-1, 1) #  vector columna
fil = v1d.reshape(1, -1) # vector fila
print(col.shape, fil.shape)
print(v1d)

(4, 1) (1, 4)
[1 2 3 4]


##Modulo_4
---

Operaciones_Elemento a Elemento

In [38]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

Operaciones_basicas

In [39]:
print(a + b) # suma elemento a elemento
print(b - a) #  resta
print(a * b) # multiplicación
print(b / a) # división donde devuelve float
print(a ** 2) # potencia
print(b // 3) # división entera
print(b % 3) # módulo


[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 1  4  9 16 25]
[ 3  6 10 13 16]
[1 2 0 1 2]


Operaciones con escalar

In [41]:
print(a)
print(b)
print(a * 2)
print(b + 10)
print(a > 3)

[1 2 3 4 5]
[10 20 30 40 50]
[ 2  4  6  8 10]
[20 30 40 50 60]
[False False False  True  True]


Matrices

In [43]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)
print(A + B) # suma elemento a elemento
print(A * B) # producto elemento a elemento
print(A @ B)
# A * B NO es el producto matricial.
# Para hacer con matrices usar A @ B se multiplica la primera fila de la primera matriz con la primera columna de segunda matriz

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


#Broadcasting

Escalar mas el vector

In [44]:
v = np.array([1, 2, 3, 4])
print(v + 10) #Hace escalarmente


[11 12 13 14]


Vector mas matriz

In [49]:
Ma = np.ones((3, 4)) # shape (3, 4)
ve = np.array([10, 20, 30, 40]) #  convierte a (1,4) → (3,4)
print(Ma + ve)

[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]


Columna mas fila

In [50]:
col = np.array([[1], [2], [3]]) # shape (3, 1) hay tres filas y una columna
fil = np.array([10, 20, 30, 40]) # shape (4,) → (1, 4) en este caso hay una fila y cuatro columnas
suma = col + fil
print(suma)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


Normalización por columna

In [51]:
datos = np.random.randint(1, 100, (5, 3))
maximos = datos.max(axis=0) # shape (3,) o (1,3) — máximo de cada columna
norm = datos / maximos # broadcasting (5,3) / (3,) → (5,3)
print(norm.round(2))


[[0.69 0.73 0.99]
 [1.   0.61 0.4 ]
 [0.9  1.   0.09]
 [0.53 0.66 0.65]
 [0.21 0.48 1.  ]]


Verificar compatibilidad

In [56]:
# Shapes incompatibles: (3,4) y (3,) → Error (sin reshape)
try:
  err = np.ones((3,4)) + np.ones(3,)
except ValueError as e:
  print('Error:', e)
# Shapes compatibles: (3,4) y (4,) → OK
try:
  err = np.ones((3,4)) + np.ones(4,)
except ValueError as e:
  print('Error:', e)

Error: operands could not be broadcast together with shapes (3,4) (3,) 


#Funciones Universales

In [ ]:
v = np.array([-4.5, -1.0, 0.0, 2.5, 9.0])


Funciones básicas

In [57]:
print(np.abs(v))
print(np.sqrt(np.abs(v))) # raíz cuadrada
print(np.square(v))
print(np.floor(v)) # redondeo hacia abajo
print(np.ceil(v)) # redondeo hacia arriba

[10 20 30 40]
[3.16227766 4.47213595 5.47722558 6.32455532]
[ 100  400  900 1600]
[10. 20. 30. 40.]
[10. 20. 30. 40.]


Exponencial y logaritmo

In [58]:
pos = np.array([1.0, 2.0, 4.0, 8.0])
print(np.log(pos)) # ln
print(np.log2(pos)) # log₂
print(np.exp(pos)) # e^x

[0.         0.69314718 1.38629436 2.07944154]
[0. 1. 2. 3.]
[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]


Trigonometría

In [60]:
angulos = np.linspace(0, 2 * np.pi, 5) # 0, π/2, π, 3π/2, 2π
print(np.sin(angulos).round(4))
print(np.cos(angulos).round(4))

[ 0.  1.  0. -1. -0.]
[ 1.  0. -1. -0.  1.]


clip sirve para limitar valores a un rango

In [61]:
datos = np.array([-10, -5, 0, 5, 10, 15, 20])
recortado = np.clip(datos, 0, 10) # valores entre 0 al 10
print(recortado)


[ 0  0  0  5 10 10 10]


maximum y minimum de elemento a elemento

In [62]:
a = np.array([3, 1, 7, 2])
b = np.array([4, 5, 2, 8])
print(np.maximum(a, b)) # máximo entre pares
print(np.minimum(a, b)) # mínimo entre pares

[4 5 7 8]
[3 1 2 2]


#Estadística y Reducciones

In [64]:
M = np.array([[4, 7, 2, 8],
              [3, 11, 5, 1],
              [6, 9, 0, 4]])
print(M)

[[ 4  7  2  8]
 [ 3 11  5  1]
 [ 6  9  0  4]]


 Reducción global

In [65]:
print(M.sum())
print(M.mean())
print(M.max())
print(M.min())

60
5.0
11
0


Reducción por eje

In [66]:
print(M.sum(axis=0)) # suma por columna
print(M.sum(axis=1)) # suma por fila
print(M.mean(axis=0)) # media de cada columna
print(M.max(axis=1)) # máximo de cada fila

[13 27  7 13]
[21 20 19]
[4.33333333 9.         2.33333333 4.33333333]
[ 8 11  9]


argmin / argmax — índice del extremo

In [67]:
print(M.argmin(axis=1)) # índice del mínimo en cada fila
print(M.argmax(axis=0)) # índice del máximo en cada columna


[2 3 2]
[2 1 1 0]


std y var

In [68]:
print(M.std()) # desviación estándar global
print(M.var(axis=0)) # varianza de cada columna


3.1885210782848317
[1.55555556 2.66666667 4.22222222 8.22222222]


keepdims sirve para mantener dimensiones

In [69]:
media = M.mean(axis=0, keepdims=True) # shape (1, 4) en vez de (4,)
print(media.shape)
centrado = M - media # broadcasting funciona directamente


(1, 4)


suma acumulada o cumsum

In [70]:
v = np.array([1, 2, 3, 4, 5])
print(np.cumsum(v))

[ 1  3  6 10 15]


percentile

In [71]:
print(np.percentile(M, 25)) # primer cuartil
print(np.median(M)) # mediana


2.75
4.5


#Concatenación y Apilamiento de Arrays

In [72]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [10, 11, 12]])


Concatenación o concatenate

In [73]:
vertical = np.concatenate([A, B], axis=0) # apilar filas
print(vertical.shape)
horizontal = np.concatenate([A, B], axis=1) # apilar columnas
print(horizontal.shape)


(4, 3)
(2, 6)


vstack y hstack

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(np.vstack([v1, v2])) # [[1 2 3], [4 5 6]] que es el shape (2,3)
print(np.hstack([v1, v2])) # [1 2 3 4 5 6] que es el shape (6,)

Para crear nuevo eje o stack

In [74]:
capas = np.stack([A, B], axis=0) # nuevo eje al frente
print(capas.shape)

(2, 2, 3)


split

In [75]:
M = np.arange(1, 25).reshape(4, 6)
partes = np.split(M, 2, axis=1) # divide en 2 a lo largo de columnas
print(partes[0].shape) # shape de (4, 3)
print(partes[1].shape) # shape de (4, 3)
filas = np.vsplit(M, 4) # divide en 4 filas individuales
print(filas[0]) # primera fila


(4, 3)
(4, 3)
[[1 2 3 4 5 6]]


#Ordenamiento y Búsqueda

In [82]:
v = np.array([5, 2, 8, 1, 9, 3, 7, 4, 6])

sort

In [83]:
ordenado = np.sort(v) # copia — v no cambia
v.sort() # in-place está ordenado
print(v)

[1 2 3 4 5 6 7 8 9]


argsort

In [79]:
v = np.array([5, 2, 8, 1, 9, 3])
idx = np.argsort(v) #  índices que ordenarían v
print(v[idx])

[1 2 3 5 8 9]


Reordenar dos arrays en paralelo

In [84]:
nombres = np.array(['Carlos','Ana','Diana','Pedro','Eva','Luis'])
notas = np.array([75, 92, 88, 61, 95, 78])
orden = np.argsort(notas)[::-1]
print(nombres[orden])
print(notas[orden])

['Eva' 'Ana' 'Diana' 'Luis' 'Carlos' 'Pedro']
[95 92 88 78 75 61]


posiciones de True que son np.where con 1 argumento

In [86]:
datos = np.array([0, 5, 0, 3, 0, 8])
pos = np.where(datos > 0) # devuelve tupla de arrays de índices
print(pos)
print(datos[pos])


(array([1, 3, 5]),)
[5 3 8]


unique

In [87]:
colores = np.array([1, 2, 1, 3, 2, 1, 4, 3])
unicos, conteos = np.unique(colores, return_counts=True)
print(unicos)
print(conteos)

[1 2 3 4]
[3 2 2 1]
